// استيراد من firebase.js
import {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    deleteProduct,
    updateProduct,
    updateProductStock,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    getOrdersWithDetails,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings
} from './firebase.js';

// إعادة تصدير كل شيء للاستخدام في الملفات الأخرى
export {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    deleteProduct,
    updateProduct,
    updateProductStock,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    getOrdersWithDetails,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings
};
