import {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    updateProduct,        // ✅ أضف هذا
    deleteProduct,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings,
    getOrdersWithCustomers
} from './firebase.js';

export {
    db,
    collection,
    addDoc,
    doc,
    getDoc,
    getDocs,
    updateDoc,
    deleteDoc,
    setDoc,
    getCollection,
    loadProducts,
    addProduct,
    updateProduct,        // ✅ أضف هذا
    deleteProduct,
    loadOrders,
    addOrder,
    updateOrder,
    deleteOrder,
    loadCustomers,
    addCustomer,
    updateCustomer,
    deleteCustomer,
    getSettings,
    setSettings,
    getOrdersWithCustomers
};
